IF DB_ID('wqp') IS NOT NULL
BEGIN
  ALTER DATABASE wqp SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
  DROP DATABASE wqp;
END;
GO

CREATE DATABASE wqp;
GO
USE wqp;
GO
CREATE SCHEMA wqp AUTHORIZATION dbo;
GO
